name: Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ansible Lint
        uses: ansible/ansible-lint-action@v6
